steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "function-2",
        "--entry-point=hello_http",
        "--region=us-central1",
        "--trigger-http",
        "--runtime=python312"
      ]
    env:
      - 'GOOGLE_FUNCTION_SOURCE=main.py' 
options:
  logging: CLOUD_LOGGING_ONLY
