steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "function_data_extract",
        "--entry-point=hello_http",
        "--region=us-central1",
        "--trigger-http",
        "--runtime=python312",
        "--source=./cloud-function/function_data_extract",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
